### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by sorinpopescu** [plentymarkets/plentymarkets-shopware-connector#408]
Shopware: 5.5.2
PHP 5.6

Error at bin/console plentyconnector:backlog:process

![image](https://user-images.githubusercontent.com/2951110/47672891-caa55400-dbbb-11e8-8d7d-e63ab6806b6d.png)

**Comment by lacodimizer** [comment]
The issue was fixed and was a error of exists article translation, because the namespace of the connector was chanced.

**Comment by lacodimizer** [comment]
This is the pr for this issue:
https://github.com/plentymarkets/plentymarkets-shopware-connector/commit/88d135047aeb051e03bfd0be61bc0acc099f19c6

**Comment by jochenmanz** [comment]
@sorinpopescu #401 and #399 fixed this behaviour. Does the migration correct your problem or are there still some products with this error?

**Comment by sorinpopescu** [comment]
@jochenmanz - all goes ok now - thanks.

I still have some issues with Prices and Orders - should I open them in a separate tikets?

**Comment by jochenmanz** [comment]
separate tickets would be perfect, thank you! :)
